version: 2

jobs:
    build:
      working_directory: ~/howitzer_example
      docker:
        - image: circleci/ruby:2.6.8-browsers
      steps:
        - checkout
        - run: git submodule update --init
        - run: sudo apt-get update
        - run: sudo apt-get install g++ qt5-default libqt5webkit5-dev gstreamer1.0-plugins-base gstreamer1.0-tools gstreamer1.0-x
        # Restore bundle cache
        - type: cache-restore
          key: example-turnip-{{ checksum "Gemfile.lock" }}

        # Bundle install dependencies
        - run: gem install bundler:2.2.22
        - run: bundle install --path vendor/bundle

        # Store bundle cache
        - type: cache-save
          key: example-turnip-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
        - run: bundle exec rake features:smoke
